<script setup lang="ts">
import { ref } from 'vue'
const autoResume = ref(true), citations = ref(true), notes = ref(true)
</script>

<template>
  <main class="page settings-page"><section class="page-heading grid-heading"><h1>设置</h1><p>所有学习内容保留在这台电脑中。</p></section><div class="database-ok"><i class="pi pi-check-circle" />本地数据库运行正常 · 上次备份：今天</div><div class="settings-grid"><section class="panel settings-main"><h2>AI 模型与连接</h2><article class="cloud-model"><i class="pi pi-cloud-download" /><div><h3>云端模型（稍后配置）</h3><span>● 未连接</span><p>仅在你发起提问时发送必要上下文</p></div><button class="primary-outline">配置模型</button></article><h2>内容来源</h2><div class="source-tabs"><button><i class="pi pi-file" />技术博客</button><button><i class="pi pi-github" />GitHub</button><button><i class="pi pi-book" />官方文档</button><button><i class="pi pi-graduation-cap" />论文</button></div><div class="source-list"><button v-for="[name, count] in [['技术博客','8 个源'],['GitHub','6 个仓库'],['官方文档','12 个站点'],['论文','6 个数据库']]" :key="name">{{ name }} <span><i class="online" />已启用</span><small>已连接 {{ count }}</small><i class="pi pi-angle-right" /></button></div><button class="primary-button wide">管理来源</button></section><aside><section class="panel local-data"><h2><i class="pi pi-database" />本地数据</h2><button v-for="[icon,text,status] in [['pi-folder','学习资料与笔记','正常'],['pi-search','全文检索索引','正常'],['pi-box','本地向量索引（后续启用）','未启用']]" :key="text"><i class="pi" :class="icon" />{{ text }}<span>{{ status }}</span><i class="pi pi-angle-right" /></button><div><button class="primary-button">立即备份</button><button class="primary-outline">打开备份位置</button></div></section><section class="panel preferences"><h2>体验偏好</h2><label> <i class="pi pi-history" />启动时恢复上次学习 <input v-model="autoResume" type="checkbox" /><b /></label><label> <i class="pi pi-link" />助手回答附带来源 <input v-model="citations" type="checkbox" /><b /></label><label> <i class="pi pi-pencil" />自动保存笔记 <input v-model="notes" type="checkbox" /><b /></label></section><section class="panel about"><strong><b>N</b> Nexus 学习站　· 0.1.0</strong><small>Tauri 2 / 桌面应用</small><button class="primary-outline">检查更新</button></section></aside></div><section class="panel data-security"><i class="pi pi-shield" /><div><h2>数据安全</h2><p>Nexus 学习站采用本地优先存储策略，所有学习资料、笔记与索引数据仅保存在你的设备中。我们不会收集、上传或共享你的任何学习数据。</p></div><button class="primary-outline"><i class="pi pi-upload" />导出学习数据</button><button class="primary-outline"><i class="pi pi-download" />导入备份</button></section>
  </main>
</template>
